/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CandidatoRouteRouteImport } from './routes/_candidato/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as PortalEntrarRouteImport } from './routes/portal.entrar'
import { Route as ETokenRouteImport } from './routes/e.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as CandidatoPortalRouteImport } from './routes/_candidato/portal'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated/super'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedNiveisRouteImport } from './routes/_authenticated/niveis'
import { Route as AuthenticatedLideresRouteImport } from './routes/_authenticated/lideres'
import { Route as AuthenticatedIdentidadeRouteImport } from './routes/_authenticated/identidade'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCatalogoRouteImport } from './routes/_authenticated/catalogo'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CandidatoPortalPerfilRouteImport } from './routes/_candidato/portal.perfil'
import { Route as CandidatoPortalCurriculoRouteImport } from './routes/_candidato/portal.curriculo'
import { Route as CandidatoPortalIdRouteImport } from './routes/_candidato/portal.$id'
import { Route as AuthenticatedPreviaIdRouteImport } from './routes/_authenticated/previa.$id'
import { Route as AuthenticatedCandidatoIdRouteImport } from './routes/_authenticated/candidato.$id'
import { Route as ApiPublicHooksAvaliacoesRouteImport } from './routes/api/public/hooks/avaliacoes'

const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRouteRoute = CandidatoRouteRouteImport.update({
  id: '/_candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEntrarRoute = PortalEntrarRouteImport.update({
  id: '/portal/entrar',
  path: '/portal/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ETokenRoute = ETokenRouteImport.update({
  id: '/e/$token',
  path: '/e/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoPortalRoute = CandidatoPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => CandidatoRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNiveisRoute = AuthenticatedNiveisRouteImport.update({
  id: '/niveis',
  path: '/niveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLideresRoute = AuthenticatedLideresRouteImport.update({
  id: '/lideres',
  path: '/lideres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentidadeRoute = AuthenticatedIdentidadeRouteImport.update({
  id: '/identidade',
  path: '/identidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoRoute = AuthenticatedCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CandidatoPortalPerfilRoute = CandidatoPortalPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CandidatoPortalRoute,
} as any)
const CandidatoPortalCurriculoRoute =
  CandidatoPortalCurriculoRouteImport.update({
    id: '/curriculo',
    path: '/curriculo',
    getParentRoute: () => CandidatoPortalRoute,
  } as any)
const CandidatoPortalIdRoute = CandidatoPortalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidatoPortalRoute,
} as any)
const AuthenticatedPreviaIdRoute = AuthenticatedPreviaIdRouteImport.update({
  id: '/previa/$id',
  path: '/previa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatoIdRoute =
  AuthenticatedCandidatoIdRouteImport.update({
    id: '/candidato/$id',
    path: '/candidato/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksAvaliacoesRoute =
  ApiPublicHooksAvaliacoesRouteImport.update({
    id: '/api/public/hooks/avaliacoes',
    path: '/api/public/hooks/avaliacoes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/identidade': typeof AuthenticatedIdentidadeRoute
  '/lideres': typeof AuthenticatedLideresRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/super': typeof AuthenticatedSuperRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/portal': typeof CandidatoPortalRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/e/$token': typeof ETokenRoute
  '/portal/entrar': typeof PortalEntrarRoute
  '/s/$code': typeof SCodeRoute
  '/candidato/$id': typeof AuthenticatedCandidatoIdRoute
  '/previa/$id': typeof AuthenticatedPreviaIdRoute
  '/portal/$id': typeof CandidatoPortalIdRoute
  '/portal/curriculo': typeof CandidatoPortalCurriculoRoute
  '/portal/perfil': typeof CandidatoPortalPerfilRoute
  '/api/public/hooks/avaliacoes': typeof ApiPublicHooksAvaliacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/catalogo': typeof AuthenticatedCatalogoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/identidade': typeof AuthenticatedIdentidadeRoute
  '/lideres': typeof AuthenticatedLideresRoute
  '/niveis': typeof AuthenticatedNiveisRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/super': typeof AuthenticatedSuperRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/portal': typeof CandidatoPortalRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/e/$token': typeof ETokenRoute
  '/portal/entrar': typeof PortalEntrarRoute
  '/s/$code': typeof SCodeRoute
  '/candidato/$id': typeof AuthenticatedCandidatoIdRoute
  '/previa/$id': typeof AuthenticatedPreviaIdRoute
  '/portal/$id': typeof CandidatoPortalIdRoute
  '/portal/curriculo': typeof CandidatoPortalCurriculoRoute
  '/portal/perfil': typeof CandidatoPortalPerfilRoute
  '/api/public/hooks/avaliacoes': typeof ApiPublicHooksAvaliacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_candidato': typeof CandidatoRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/catalogo': typeof AuthenticatedCatalogoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/identidade': typeof AuthenticatedIdentidadeRoute
  '/_authenticated/lideres': typeof AuthenticatedLideresRoute
  '/_authenticated/niveis': typeof AuthenticatedNiveisRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/super': typeof AuthenticatedSuperRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_candidato/portal': typeof CandidatoPortalRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/e/$token': typeof ETokenRoute
  '/portal/entrar': typeof PortalEntrarRoute
  '/s/$code': typeof SCodeRoute
  '/_authenticated/candidato/$id': typeof AuthenticatedCandidatoIdRoute
  '/_authenticated/previa/$id': typeof AuthenticatedPreviaIdRoute
  '/_candidato/portal/$id': typeof CandidatoPortalIdRoute
  '/_candidato/portal/curriculo': typeof CandidatoPortalCurriculoRoute
  '/_candidato/portal/perfil': typeof CandidatoPortalPerfilRoute
  '/api/public/hooks/avaliacoes': typeof ApiPublicHooksAvaliacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/admin'
    | '/catalogo'
    | '/dashboard'
    | '/identidade'
    | '/lideres'
    | '/niveis'
    | '/permissoes'
    | '/planos'
    | '/super'
    | '/usuarios'
    | '/portal'
    | '/c/$token'
    | '/e/$token'
    | '/portal/entrar'
    | '/s/$code'
    | '/candidato/$id'
    | '/previa/$id'
    | '/portal/$id'
    | '/portal/curriculo'
    | '/portal/perfil'
    | '/api/public/hooks/avaliacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/definir-senha'
    | '/admin'
    | '/catalogo'
    | '/dashboard'
    | '/identidade'
    | '/lideres'
    | '/niveis'
    | '/permissoes'
    | '/planos'
    | '/super'
    | '/usuarios'
    | '/portal'
    | '/c/$token'
    | '/e/$token'
    | '/portal/entrar'
    | '/s/$code'
    | '/candidato/$id'
    | '/previa/$id'
    | '/portal/$id'
    | '/portal/curriculo'
    | '/portal/perfil'
    | '/api/public/hooks/avaliacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_candidato'
    | '/auth'
    | '/definir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/catalogo'
    | '/_authenticated/dashboard'
    | '/_authenticated/identidade'
    | '/_authenticated/lideres'
    | '/_authenticated/niveis'
    | '/_authenticated/permissoes'
    | '/_authenticated/planos'
    | '/_authenticated/super'
    | '/_authenticated/usuarios'
    | '/_candidato/portal'
    | '/c/$token'
    | '/e/$token'
    | '/portal/entrar'
    | '/s/$code'
    | '/_authenticated/candidato/$id'
    | '/_authenticated/previa/$id'
    | '/_candidato/portal/$id'
    | '/_candidato/portal/curriculo'
    | '/_candidato/portal/perfil'
    | '/api/public/hooks/avaliacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CandidatoRouteRoute: typeof CandidatoRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  CTokenRoute: typeof CTokenRoute
  ETokenRoute: typeof ETokenRoute
  PortalEntrarRoute: typeof PortalEntrarRoute
  SCodeRoute: typeof SCodeRoute
  ApiPublicHooksAvaliacoesRoute: typeof ApiPublicHooksAvaliacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_candidato': {
      id: '/_candidato'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CandidatoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/entrar': {
      id: '/portal/entrar'
      path: '/portal/entrar'
      fullPath: '/portal/entrar'
      preLoaderRoute: typeof PortalEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$token': {
      id: '/e/$token'
      path: '/e/$token'
      fullPath: '/e/$token'
      preLoaderRoute: typeof ETokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_candidato/portal': {
      id: '/_candidato/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof CandidatoPortalRouteImport
      parentRoute: typeof CandidatoRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/niveis': {
      id: '/_authenticated/niveis'
      path: '/niveis'
      fullPath: '/niveis'
      preLoaderRoute: typeof AuthenticatedNiveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lideres': {
      id: '/_authenticated/lideres'
      path: '/lideres'
      fullPath: '/lideres'
      preLoaderRoute: typeof AuthenticatedLideresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identidade': {
      id: '/_authenticated/identidade'
      path: '/identidade'
      fullPath: '/identidade'
      preLoaderRoute: typeof AuthenticatedIdentidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo': {
      id: '/_authenticated/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AuthenticatedCatalogoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_candidato/portal/perfil': {
      id: '/_candidato/portal/perfil'
      path: '/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof CandidatoPortalPerfilRouteImport
      parentRoute: typeof CandidatoPortalRoute
    }
    '/_candidato/portal/curriculo': {
      id: '/_candidato/portal/curriculo'
      path: '/curriculo'
      fullPath: '/portal/curriculo'
      preLoaderRoute: typeof CandidatoPortalCurriculoRouteImport
      parentRoute: typeof CandidatoPortalRoute
    }
    '/_candidato/portal/$id': {
      id: '/_candidato/portal/$id'
      path: '/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof CandidatoPortalIdRouteImport
      parentRoute: typeof CandidatoPortalRoute
    }
    '/_authenticated/previa/$id': {
      id: '/_authenticated/previa/$id'
      path: '/previa/$id'
      fullPath: '/previa/$id'
      preLoaderRoute: typeof AuthenticatedPreviaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidato/$id': {
      id: '/_authenticated/candidato/$id'
      path: '/candidato/$id'
      fullPath: '/candidato/$id'
      preLoaderRoute: typeof AuthenticatedCandidatoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/avaliacoes': {
      id: '/api/public/hooks/avaliacoes'
      path: '/api/public/hooks/avaliacoes'
      fullPath: '/api/public/hooks/avaliacoes'
      preLoaderRoute: typeof ApiPublicHooksAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCatalogoRoute: typeof AuthenticatedCatalogoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIdentidadeRoute: typeof AuthenticatedIdentidadeRoute
  AuthenticatedLideresRoute: typeof AuthenticatedLideresRoute
  AuthenticatedNiveisRoute: typeof AuthenticatedNiveisRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedCandidatoIdRoute: typeof AuthenticatedCandidatoIdRoute
  AuthenticatedPreviaIdRoute: typeof AuthenticatedPreviaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCatalogoRoute: AuthenticatedCatalogoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIdentidadeRoute: AuthenticatedIdentidadeRoute,
  AuthenticatedLideresRoute: AuthenticatedLideresRoute,
  AuthenticatedNiveisRoute: AuthenticatedNiveisRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedSuperRoute: AuthenticatedSuperRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedCandidatoIdRoute: AuthenticatedCandidatoIdRoute,
  AuthenticatedPreviaIdRoute: AuthenticatedPreviaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CandidatoPortalRouteChildren {
  CandidatoPortalIdRoute: typeof CandidatoPortalIdRoute
  CandidatoPortalCurriculoRoute: typeof CandidatoPortalCurriculoRoute
  CandidatoPortalPerfilRoute: typeof CandidatoPortalPerfilRoute
}

const CandidatoPortalRouteChildren: CandidatoPortalRouteChildren = {
  CandidatoPortalIdRoute: CandidatoPortalIdRoute,
  CandidatoPortalCurriculoRoute: CandidatoPortalCurriculoRoute,
  CandidatoPortalPerfilRoute: CandidatoPortalPerfilRoute,
}

const CandidatoPortalRouteWithChildren = CandidatoPortalRoute._addFileChildren(
  CandidatoPortalRouteChildren,
)

interface CandidatoRouteRouteChildren {
  CandidatoPortalRoute: typeof CandidatoPortalRouteWithChildren
}

const CandidatoRouteRouteChildren: CandidatoRouteRouteChildren = {
  CandidatoPortalRoute: CandidatoPortalRouteWithChildren,
}

const CandidatoRouteRouteWithChildren = CandidatoRouteRoute._addFileChildren(
  CandidatoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CandidatoRouteRoute: CandidatoRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  CTokenRoute: CTokenRoute,
  ETokenRoute: ETokenRoute,
  PortalEntrarRoute: PortalEntrarRoute,
  SCodeRoute: SCodeRoute,
  ApiPublicHooksAvaliacoesRoute: ApiPublicHooksAvaliacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
